KBBWRPC ; VEN/ARC - PATIENT EHR RPC ; 11/5/2015
 ;;1.0;NONE;**LOCAL**; NOV 5, 2015
 ;
USERID(XDFN)
 K XDFN
 Q:'DUZ
 S XDFN=DUZ_U_$P($G(^VA(200,DUZ,0)),U)_U
 ; W XDFN,!
 N KEY S KEY=+$O(^DIC(19.1,"B","KBBWFA",0))
 ; W KEY,!
 S:KEY KEY=$D(^VA(200,DUZ,51,KEY,0))
 ; W KEY,!
 S:KEY XDFN=XDFN_"KBBWFA"_U
 ; W XDFN,!
 Q
